<a href="https://colab.research.google.com/github/DarellYuhu/data-analytics-training/blob/master/Order.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
from datetime import datetime, timedelta
from google.colab import files

uploaded = files.upload()

Saving Products.csv to Products (1).csv

In [5]:
from google.colab import files

uploaded = files.upload()

Saving customers.csv to customers.csv

In [54]:
products = pd.read_csv("Products.csv")
customers = pd.read_csv("customers.csv")

In [9]:
products.head()

,ProductID,ProductName,category,unitCost,UnitPrice,supplier,IsActive
0,1,Gaming Mouse,Accessories,295,442.5,Prime Devices,True
1,2,27-inch Monitor,Laptop,31,46.5,Prime Devices,True
2,3,Portable SSD,audio,132,198.0,Prime Devices,True
3,4,Gaming Mouse,office,241,361.5,Prime Devices,True
4,5,Smart Watch,storage,220,330.0,Prime Devices,True

In [10]:
customers.head()

,customer_id,name,email,acquisition_date,acquisition_channel,city,state
0,1,Ryan Nixon,ryan.nixon1@gmail.com,2026-06-11,Google,Makassar,South Sulawesi
1,2,Thomas Shepard,thomas.shepard2@gmail.com,2025-02-07,TikTok,Yogyakarta,DI Yogyakarta
2,3,Alexis Kelly,alexis.kelly3@gmail.com,2024-10-15,TikTok,Medan,North Sumatra
3,4,Amanda Campbell,amanda.campbell4@gmail.com,2025-12-28,Organic,Denpasar,Bali
4,5,Clayton Harris,clayton.harris5@gmail.com,2025-04-25,Organic,Surabaya,East Java

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          5000 non-null   int64
 1   name                 5000 non-null   object
 2   email                5000 non-null   object
 3   acquisition_date     5000 non-null   object
 4   acquisition_channel  5000 non-null   object
 5   city                 5000 non-null   object
 6   state                5000 non-null   object
dtypes: int64(1), object(6)
memory usage: 273.6+ KB

In [14]:
print(products.shape)
print(customers.shape)

(200, 7)
(5000, 7)

In [15]:
num_orders = 15000

orders = []

order_statuses = [
    "Delivered",
    "Canceled",
    "Returned"
]

status_weights = [90, 5, 5]

payment_methods = [
    "Credit Card",
    "Paypal",
    "Bank Tranfer",
    "E-Waller",
    "Cash On Delivery"
]

payment_weights = [35, 20, 15,25,5]

In [18]:
order_id = 1

In [44]:
import random
customer_id = random.choice(
    customers["customer_id"].tolist()
)

In [24]:
customer = customers[
    customers["customer_id"] == customer_id
].iloc[0]

In [25]:
acquisition_date = pd.to_datetime(
    customer["acquisition_date"]
)

In [30]:
today = datetime.today()

In [36]:
days_since_signup = (
    today - acquisition_date
).days

In [37]:
order_date = acquisition_date + timedelta(
    days=random.randint(0, days_since_signup)
)

In [38]:
order_date = order_date.date()

In [49]:
status = random.choices(
    order_statuses,
    weights=status_weights,
    k=1
)[0]

payment_method = random.choices(
    payment_methods,
    weights=payment_weights,
    k=1
)[0]

In [50]:
order = {
    "order_id": order_id,
    "customer_id": customer_id,
    "order_date": order_date,
    "order_status": status,
    "payment_method": payment_method
}

In [51]:
print(order)

{'order_id': 1, 'customer_id': 522, 'order_date': datetime.date(2026, 7, 4), 'order_status': 'Delivered', 'payment_method': 'E-Waller'}

In [55]:
orders = []

for i in range(num_orders):

    order_id = i + 1

    customer_id = random.choice(
        customers["customer_id"].tolist()
    )

    customer = customers[
        customers["customer_id"] == customer_id
    ].iloc[0]

    acquisition_date = pd.to_datetime(
        customer["acquisition_date"]
    )

    today = datetime.today()

    days_since_signup = (
        today - acquisition_date
    ).days

    order_date = (
        acquisition_date
        + timedelta(days=random.randint(0, days_since_signup))
    ).date()

    status = random.choices(
        order_statuses,
        weights=status_weights,
        k=1
    )[0]

    payment_method = random.choices(
        payment_methods,
        weights=payment_weights,
        k=1
    )[0]

    order = {
        "order_id": order_id,
        "customer_id": customer_id,
        "order_date": order_date,
        "order_status": status,
        "payment_method": payment_method
    }

    orders.append(order)

In [56]:
df_orders = pd.DataFrame(orders)

In [57]:
df_orders.head()

   order_id  customer_id  order_date order_status payment_method
0         1         3175  2025-11-18    Delivered    Credit Card
1         2         3818  2025-10-21    Delivered       E-Waller
2         3          119  2026-01-02    Delivered   Bank Tranfer
3         4         3758  2026-06-30    Delivered       E-Waller
4         5         4027  2025-06-03    Delivered    Credit Card

In [59]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        15000 non-null  int64
 1   customer_id     15000 non-null  int64
 2   order_date      15000 non-null  object
 3   order_status    15000 non-null  object
 4   payment_method  15000 non-null  object
dtypes: int64(2), object(3)
memory usage: 586.1+ KB

In [60]:
len(df_orders)

15000

In [61]:
df_orders["order_id"].is_unique

True

In [62]:
df_orders["customer_id"].isin(
    customers["customer_id"]
).all()

np.True_

In [63]:
df_orders["order_status"].value_counts()

order_status
Delivered    13428
Returned       838
Canceled       734
Name: count, dtype: int64

In [65]:
df_orders["payment_method"].value_counts()

payment_method
Credit Card         5335
E-Waller            3761
Paypal              2995
Bank Tranfer        2188
Cash On Delivery     721
Name: count, dtype: int64

In [66]:
df_orders["customer_id"].value_counts().head(10)

customer_id
964     10
738     10
897     10
2743     9
2666     9
3868     9
1047     9
1980     9
684      9
2687     9
Name: count, dtype: int64

In [67]:
df_orders.to_csv("orders.csv", index=False)